<script src="{{ mix('assets/js/all.js') }}"></script>
<script>
    window.translations = {
        show: "{{ __('backend.Show') }}",
        entries: "{{ __('backend.entries') }}",
        Search: "{{ __('backend.Search:') }}",
        Showing: "{{ __('backend.Showing') }}",
        NoData: "{{ __('backend.No data available in table') }}",
        to: "{{ __('backend.to') }}",
        nameOfItem: "{{ __('backend.name of Item') }}",
        of: "{{ __('backend.of') }}",
        noRecord: "{{ __('backend.No matching records found') }}",
        deletemodal1: "{{ __('backend.Are you sure ?') }}",
        deletemodal2: "{{ __('backend.You wont be able to revert this!') }}",
        cancle: "{{ __('backend.Cancel') }}",
        confirm: "{{ __('backend.confirm') }}",
        deleted: "{{ __('backend.Deleted!') }}",
        success: "{{ __('backend.file has been deleted successfully.') }}",
        continue: "{{ __('backend.continue') }}",
        nameOfProject: "{{ __('backend.name of project') }}",
        description: "{{ __('backend.description') }}",
        startingFrom: "{{ __('backend.Starting From') }}",
        endingIn: "{{ __('backend.Ending In') }}",
        email: "{{ __('backend.email') }}",
        projectDetails: "{{ __('backend.Project details') }}",

    };
    window.translation = {
        deletemodal1: "{{ __('backend.Are you sure ?') }}",
        deletemodal2: "{{ __('backend.You wont be able to revert this!') }}",
        cancle: "{{ __('backend.Cancel') }}",
        confirm: "{{ __('backend.confirm') }}",
        deleted: "{{ __('backend.Deleted!') }}",
        success: "{{ __('backend.file has been deleted successfully.') }}",
        continue: "{{ __('backend.continue') }}",
        userInfo: "{{ __('backend.userInfo') }}",
        email: "{{ __('backend.email') }}",
        userName: "{{ __('backend.name') }}",
        phone: "{{ __('backend.phone') }}",
        UserType: "{{ __('backend.UserType') }}",
        nameactivities: "{{ __('backend.name of activities') }}",
        save: "{{ __('backend.save') }}",
        QuotesDetails: "{{ __('backend.QuotesDetails') }}",
        Accepttheoffer: "{{ __('backend.Accept the offer') }}",
        offerrejected: "{{ __('backend.offer rejected') }}",
        Refundetails: "{{ __('backend.Refund request details') }}",
        amount: "{{ __('backend.the amount') }}",
        beneficiary: "{{ __('backend.beneficiary') }}",
        Createdat: "{{ __('backend.Created at') }}",
        Membership: "{{ __('backend.Membership No') }}",
        IBAN: "{{ __('backend.Account number IBAN') }}",
        Download: "{{ __('backend.Download the attached image') }}",
        sendComment: "{{ __('frontend.sendComment') }}",
        attach: "{{ __('backend.attach a picture') }}",
        Typemessage: "{{ __('backend.Type a message..') }}",
        Contractdetails: "{{ __('backend.Contract details') }}",
        ContractID: "{{ __('backend.contract number') }}",
        typeCompany: "{{ __('backend.company type') }}",
        CommercialRecord: "{{ __('backend.Commercial record') }}",
        company_name: "{{ __('backend.name of company') }}",
        BriefDescription: "{{ __('backend.Brief description') }}",
        City: "{{ __('backend.city') }}",
        renewable: "{{ __('backend.renewable') }}",
        fbatch: "{{ __('backend.The first batch') }}",
        sbatch: "{{ __('backend.second batch') }}",
        tbatch: "{{ __('backend.third batch') }}",
        finalBatch: "{{ __('backend.final batch') }}",
        Datecontract: "{{ __('backend.Date of contract') }}",
        sDatecontract: "{{ __('backend.Contract start date') }}",
        eDatecontract: "{{ __('backend.Contract end date') }}",
        Attachedcontract: "{{ __('backend.Attached contract file') }}",
        downloadcontact: "{{ __('backend.Download the attached contract file') }}",
        Invoices: "{{ __('backend.Invoices') }}",
    };
</script>
<!-- Stack array for including inline js or scripts -->
@stack('plugin-scripts')

@stack('custom-scripts')
